steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "builds",
        "submit",
        "--project",
        "${_PROJECT_ID}",
        "--tag",
        "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_IMAGE}:${_TAG}",
      ]
    dir: "discord-bot"
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "discord-bot",
        "--project",
        "${_PROJECT_ID}",
        "--image",
        "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_IMAGE}:${_TAG}",
        "--region",
        "${_REGION}",
        "--set-env-vars",
        "IS_PRODUCTION=1",
        "--set-secrets",
        "/etc/discord-bot-api-token/secret=discord-bot-api-token:latest",
        "--min-instances",
        "1",
        "--max-instances",
        "1",
        "--cpu",
        "1",
        "--memory",
        "512Mi",
        "--no-allow-unauthenticated",
        "--no-cpu-throttling",
        "--service-account",
        "chibawest-gamecenter-bot@chibawest-gamecenter.iam.gserviceaccount.com",
      ]
    dir: "discord-bot"
substitutions:
  _PROJECT_ID: chibawest-gamecenter
  _REGION: asia-northeast1
  _REPOSITORY: chibawest-gamecenter
  _IMAGE: discord-bot
  _TAG: latest
